// Single source of truth for hospital metadata, navigation menus,
// departments, doctors, services, and demo data.

// Canonical deployment URL. Override with NEXT_PUBLIC_SITE_URL in env.
export const siteConfig = {
  name: "Providence General Hospital",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://www.providencegeneral.org",
  ogImage: "/opengraph-image.png",
};

export const hospitalInfo = {
  name: "Providence General Hospital",
  shortName: "Providence Health",
  tagline: "Advanced clinical care, compassionate service, 24/7 readiness.",
  establishedYear: 1984,
  licenseNumber: "MED-HOSP-NY-8942",
  phone: {
    emergency: "+1 (800) 555-0911",
    ambulance: "+1 (800) 555-0911",
    appointments: "+1 (800) 555-0144",
    general: "+1 (800) 555-0199",
  },
  email: "care@providencegeneral.org",
  address: {
    street: "742 Evergreen Medical Parkway, Suite 100",
    city: "Metro City",
    state: "NY",
    zip: "10001",
    directionsUrl: "https://maps.google.com",
  },
  hours: {
    emergency: "24 hours / 7 days / 365 days a year",
    outpatient: "Mon – Fri: 7:30 AM – 7:00 PM | Sat: 8:00 AM – 3:00 PM",
    diagnostics: "Mon – Sat: 6:30 AM – 8:00 PM | Sun: 8:00 AM – 2:00 PM",
    visitingHours: "Daily: 9:00 AM – 8:00 PM (ICU: 11:00 AM – 2:00 PM & 5:00 PM – 7:00 PM)",
    pharmacy: "24/7 In-House Service",
  },
  accreditations: [
    "Joint Commission (JCAHO) Gold Seal Certified",
    "Level I Trauma Center & Comprehensive Stroke Center",
    "Magnet Recognized for Nursing Excellence",
  ],
};

export const emergencyHotlines = [
  {
    title: "Ambulance & Trauma Resuscitation",
    phone: "+1 (800) 555-0911",
    subtitle: "Direct line to hospital dispatch (24/7)",
    urgent: true,
  },
  {
    title: "Acute Stroke & Chest Pain Triage",
    phone: "+1 (800) 555-0922",
    subtitle: "Rapid intervention team on standby",
    urgent: true,
  },
  {
    title: "Pediatric Emergency Desk",
    phone: "+1 (800) 555-0933",
    subtitle: "Dedicated pediatric trauma bay",
    urgent: false,
  },
  {
    title: "National Poison Control Center",
    phone: "1-800-222-1222",
    subtitle: "Free, confidential 24/7 guidance",
    urgent: false,
  },
];

export const publicNav = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Departments", href: "/departments" },
  { label: "Doctors", href: "/doctors" },
  { label: "Resources", href: "/resources" },
  { label: "Contact", href: "/contact" },
];

export const legalNav = [
  { label: "Privacy Policy", href: "/legal/privacy" },
  { label: "Terms of Use", href: "/legal/terms" },
  { label: "Accessibility", href: "/legal/accessibility" },
];

export const appNav = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Appointments", href: "/dashboard/appointments" },
  { label: "Telehealth Room", href: "/dashboard/telehealth" },
  { label: "Care Messages", href: "/dashboard/messages" },
  { label: "Medical Records", href: "/dashboard/records" },
  { label: "Prescriptions", href: "/dashboard/prescriptions" },
  { label: "Billing & Invoices", href: "/dashboard/billing" },
  { label: "Staff Workstation", href: "/staff" },
  { label: "Profile", href: "/profile" },
  { label: "Settings", href: "/settings" },
];

export const departments = [
  {
    id: "dept-cardiology",
    slug: "cardiology",
    name: "Cardiology & Vascular Medicine",
    shortName: "Cardiology",
    icon: "heart",
    description:
      "Comprehensive cardiovascular care, interventional catheterization, electrophysiology, and advanced heart failure treatment.",
    headOfDept: "Dr. Sarah Jenkins, MD, FACC",
    location: "Pavilion A, 3rd Floor",
    phoneExt: "Ext. 3100",
    emergencySupported: true,
    services: [
      "Diagnostic Echocardiography & ECG",
      "Cardiac Catheterization & Angioplasty",
      "Pacemaker & Defibrillator Implantation",
      "Cardiac Rehabilitation Program",
    ],
  },
  {
    id: "dept-neurology",
    slug: "neurology",
    name: "Neurology & Neurosurgery",
    shortName: "Neurology",
    icon: "brain",
    description:
      "Dedicated diagnosis and minimally invasive surgical management for stroke, epilepsy, spinal trauma, and neurodegenerative disorders.",
    headOfDept: "Dr. Marcus Vance, MD, PhD",
    location: "Pavilion B, 4th Floor",
    phoneExt: "Ext. 4200",
    emergencySupported: true,
    services: [
      "24/7 Acute Stroke Intervention",
      "Minimally Invasive Brain & Spine Surgery",
      "Comprehensive Epilepsy Monitoring",
      "Neuro-Rehabilitation & Physical Therapy",
    ],
  },
  {
    id: "dept-pediatrics",
    slug: "pediatrics",
    name: "Pediatrics & Neonatology",
    shortName: "Pediatrics",
    icon: "baby",
    description:
      "Compassionate, specialized clinical care for infants, children, and teenagers, supported by a Level III Neonatal Intensive Care Unit (NICU).",
    headOfDept: "Dr. Elena Rostova, MD, FAAP",
    location: "Children's Health Pavilion, 2nd Floor",
    phoneExt: "Ext. 2100",
    emergencySupported: true,
    services: [
      "Well-Child Exams & Immunizations",
      "Level III Neonatal ICU (NICU)",
      "Pediatric Allergy & Pulmonology",
      "Pediatric Emergency Triage",
    ],
  },
  {
    id: "dept-orthopedics",
    slug: "orthopedics",
    name: "Orthopedics & Joint Replacement",
    shortName: "Orthopedics",
    icon: "bone",
    description:
      "Pioneering robotic joint replacement, sports injury reconstruction, spinal correction, and physical therapy rehabilitation.",
    headOfDept: "Dr. David Chen, MD, FAAOS",
    location: "Pavilion C, 1st Floor",
    phoneExt: "Ext. 1500",
    emergencySupported: true,
    services: [
      "Robotic Total Hip & Knee Replacement",
      "Arthroscopic Sports Medicine",
      "Complex Fracture & Trauma Care",
      "Dedicated Outpatient Physical Therapy",
    ],
  },
  {
    id: "dept-oncology",
    slug: "oncology",
    name: "Oncology & Comprehensive Cancer Center",
    shortName: "Oncology",
    icon: "ribbon",
    description:
      "Precision oncology with multidisciplinary tumor boards, advanced radiation therapy, targeted immunotherapy, and supportive patient care.",
    headOfDept: "Dr. Amina Al-Mansoor, MD",
    location: "Hope Pavilion, 5th Floor",
    phoneExt: "Ext. 5100",
    emergencySupported: false,
    services: [
      "Chemotherapy & Targeted Immunotherapy",
      "Precision Stereotactic Radiosurgery",
      "Genetic Cancer Risk Assessment",
      "Oncology Nutrition & Psychological Support",
    ],
  },
  {
    id: "dept-obstetrics",
    slug: "obstetrics-gynecology",
    name: "Obstetrics & Women's Health",
    shortName: "Women's Health",
    icon: "female",
    description:
      "Comprehensive maternal-fetal medicine, private labor and delivery suites, gynecologic surgery, and holistic reproductive health.",
    headOfDept: "Dr. Robert Gallagher, MD, FACOG",
    location: "Women's Health Center, 2nd Floor",
    phoneExt: "Ext. 2400",
    emergencySupported: true,
    services: [
      "High-Risk Prenatal Care",
      "Private Family Birthing Suites",
      "Minimally Invasive Gynecological Surgery",
      "Menopause & Hormonal Health Clinic",
    ],
  },
  {
    id: "dept-emergency",
    slug: "emergency-trauma",
    name: "Emergency Medicine & Level I Trauma",
    shortName: "Emergency",
    icon: "ambulance",
    description:
      "Round-the-clock emergency medical services, rapid resuscitation bays, certified trauma surgeons, and acute triage.",
    headOfDept: "Dr. Priya Patel, MD, FACEP",
    location: "Ground Floor East Entrance",
    phoneExt: "Ext. 9110",
    emergencySupported: true,
    services: [
      "24/7 Level I Trauma Care",
      "Rapid Chest Pain Assessment",
      "Acute Stroke & TPA Administration",
      "Dedicated Pediatric ER Bay",
    ],
  },
  {
    id: "dept-radiology",
    slug: "radiology-imaging",
    name: "Diagnostic Radiology & Imaging",
    shortName: "Radiology",
    icon: "scan",
    description:
      "Advanced 3T MRI, 128-slice dual-source CT, digital 3D mammography, nuclear medicine, and ultrasound diagnostics.",
    headOfDept: "Dr. Michael Thorne, MD, FACR",
    location: "Central Diagnostics, Lower Level 1",
    phoneExt: "Ext. 1200",
    emergencySupported: true,
    services: [
      "High-Field 3.0T MRI & CT Scans",
      "3D Digital Tomosynthesis Mammography",
      "Ultrasound & Doppler Vascular Imaging",
      "Interventional Radiology Biopsies",
    ],
  },
];

export const doctors = [
  {
    id: "doc-sarah-jenkins",
    name: "Dr. Sarah Jenkins",
    title: "Chief of Cardiovascular Medicine",
    specialty: "Cardiology",
    departmentId: "dept-cardiology",
    departmentSlug: "cardiology",
    qualifications: "MD (Johns Hopkins), FACC, FSCAI",
    experienceYears: 18,
    languages: ["English", "Spanish"],
    consultationFee: "$180",
    rating: 4.9,
    reviewCount: 342,
    availableDays: ["Monday", "Tuesday", "Thursday"],
    availableSlots: ["09:00 AM", "10:30 AM", "01:30 PM", "03:00 PM", "04:30 PM"],
    bio: "Dr. Jenkins is a nationally recognized interventional cardiologist specializing in complex coronary interventions, heart failure management, and preventive cardiology.",
    contactEmail: "s.jenkins@providencegeneral.org",
  },
  {
    id: "doc-marcus-vance",
    name: "Dr. Marcus Vance",
    title: "Director of Neurosurgery",
    specialty: "Neurology",
    departmentId: "dept-neurology",
    departmentSlug: "neurology",
    qualifications: "MD, PhD (Harvard Medical School), FAANS",
    experienceYears: 21,
    languages: ["English"],
    consultationFee: "$220",
    rating: 4.95,
    reviewCount: 289,
    availableDays: ["Tuesday", "Wednesday", "Friday"],
    availableSlots: ["08:30 AM", "10:00 AM", "11:30 AM", "02:00 PM"],
    bio: "Dr. Vance specializes in robotic neurosurgery, minimally invasive spine reconstruction, and cerebral aneurysm repair.",
    contactEmail: "m.vance@providencegeneral.org",
  },
  {
    id: "doc-elena-rostova",
    name: "Dr. Elena Rostova",
    title: "Head of Pediatric Care",
    specialty: "Pediatrics",
    departmentId: "dept-pediatrics",
    departmentSlug: "pediatrics",
    qualifications: "MD (Columbia University), FAAP",
    experienceYears: 14,
    languages: ["English", "Russian"],
    consultationFee: "$140",
    rating: 4.92,
    reviewCount: 410,
    availableDays: ["Monday", "Wednesday", "Thursday", "Friday"],
    availableSlots: ["09:00 AM", "10:00 AM", "11:00 AM", "01:00 PM", "02:30 PM", "04:00 PM"],
    bio: "Dr. Rostova is dedicated to family-centered pediatric care, child development, and the management of chronic childhood illnesses.",
    contactEmail: "e.rostova@providencegeneral.org",
  },
  {
    id: "doc-david-chen",
    name: "Dr. David Chen",
    title: "Senior Orthopedic Surgeon",
    specialty: "Orthopedics",
    departmentId: "dept-orthopedics",
    departmentSlug: "orthopedics",
    qualifications: "MD (Stanford University), FAAOS",
    experienceYears: 16,
    languages: ["English", "Mandarin"],
    consultationFee: "$190",
    rating: 4.88,
    reviewCount: 315,
    availableDays: ["Monday", "Wednesday", "Friday"],
    availableSlots: ["08:00 AM", "09:30 AM", "11:00 AM", "01:30 PM", "03:00 PM"],
    bio: "Dr. Chen is a pioneer in computer-navigated robotic joint replacements and minimally invasive arthroscopic sports injury treatments.",
    contactEmail: "d.chen@providencegeneral.org",
  },
  {
    id: "doc-amina-almansoor",
    name: "Dr. Amina Al-Mansoor",
    title: "Lead Medical Oncologist",
    specialty: "Oncology",
    departmentId: "dept-oncology",
    departmentSlug: "oncology",
    qualifications: "MD (Oxford University), MRCP, FASCO",
    experienceYears: 17,
    languages: ["English", "Arabic", "French"],
    consultationFee: "$200",
    rating: 4.96,
    reviewCount: 260,
    availableDays: ["Monday", "Tuesday", "Thursday"],
    availableSlots: ["10:00 AM", "11:30 AM", "02:00 PM", "03:30 PM"],
    bio: "Dr. Al-Mansoor specializes in precision targeted oncology, novel clinical trials, and personalized immunotherapy protocols.",
    contactEmail: "a.almansoor@providencegeneral.org",
  },
  {
    id: "doc-robert-gallagher",
    name: "Dr. Robert Gallagher",
    title: "Director of Maternal-Fetal Medicine",
    specialty: "Obstetrics & Gynecology",
    departmentId: "dept-obstetrics",
    departmentSlug: "obstetrics-gynecology",
    qualifications: "MD (UCSF), FACOG",
    experienceYears: 19,
    languages: ["English"],
    consultationFee: "$170",
    rating: 4.91,
    reviewCount: 375,
    availableDays: ["Tuesday", "Wednesday", "Thursday"],
    availableSlots: ["09:00 AM", "10:30 AM", "01:00 PM", "02:30 PM", "04:00 PM"],
    bio: "Dr. Gallagher has delivered over 3,000 infants and has special expertise in high-risk obstetrics and advanced fetal ultrasound monitoring.",
    contactEmail: "r.gallagher@providencegeneral.org",
  },
  {
    id: "doc-priya-patel",
    name: "Dr. Priya Patel",
    title: "Clinical Director of Emergency Medicine",
    specialty: "Emergency Medicine",
    departmentId: "dept-emergency",
    departmentSlug: "emergency-trauma",
    qualifications: "MD (Penn Medicine), FACEP",
    experienceYears: 15,
    languages: ["English", "Hindi", "Gujarati"],
    consultationFee: "$160",
    rating: 4.94,
    reviewCount: 520,
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    availableSlots: ["24/7 Emergency Triage Rotation"],
    bio: "Dr. Patel leads the emergency resuscitation bay and Level I trauma team with expertise in acute airway management and disaster preparedness.",
    contactEmail: "p.patel@providencegeneral.org",
  },
  {
    id: "doc-michael-thorne",
    name: "Dr. Michael Thorne",
    title: "Chief of Diagnostic Imaging",
    specialty: "Radiology",
    departmentId: "dept-radiology",
    departmentSlug: "radiology-imaging",
    qualifications: "MD (Yale University), FACR",
    experienceYears: 20,
    languages: ["English"],
    consultationFee: "$150",
    rating: 4.87,
    reviewCount: 198,
    availableDays: ["Monday", "Tuesday", "Wednesday", "Friday"],
    availableSlots: ["08:30 AM", "10:00 AM", "01:00 PM", "03:00 PM"],
    bio: "Dr. Thorne is an expert in neuroradiology, oncologic imaging, and 3T MRI diagnostics.",
    contactEmail: "m.thorne@providencegeneral.org",
  },
];

export const services = [
  {
    id: "serv-emergency",
    name: "24/7 Emergency & Level I Trauma",
    category: "Critical Care",
    description:
      "Fully staffed trauma center with immediate surgical capabilities, rapid CT access, and pediatric emergency bays.",
    badge: "24/7 Available",
  },
  {
    id: "serv-diagnostics",
    name: "Diagnostic Laboratory & Imaging",
    category: "Diagnostics",
    description:
      "Same-day routine and specialized blood tests, 3T MRI, 128-slice CT scans, digital ultrasound, and pathology.",
    badge: "Same-Day Results",
  },
  {
    id: "serv-surgery",
    name: "Minimally Invasive & Robotic Surgery",
    category: "Surgical Care",
    description:
      "State-of-the-art da Vinci robotic surgery suites minimizing recovery time, pain, and hospital stay durations.",
    badge: "Advanced Tech",
  },
  {
    id: "serv-checkups",
    name: "Comprehensive Preventive Health Packages",
    category: "Wellness & Prevention",
    description:
      "Customized executive wellness screenings, cardiovascular risk profiles, and cancer prevention assessments.",
    badge: "Preventive",
  },
  {
    id: "serv-telehealth",
    name: "Telehealth & Virtual Consultations",
    category: "Outpatient",
    description:
      "Secure, encrypted video consultations with board-certified physicians for follow-ups, minor illnesses, and prescriptions.",
    badge: "Virtual Care",
  },
  {
    id: "serv-pharmacy",
    name: "24/7 In-House Patient Pharmacy",
    category: "Pharmacy",
    description:
      "On-site prescription fulfillment, medication reconciliation, and pharmacist consultations around the clock.",
    badge: "24/7 Service",
  },
];

// Demo patient used to seed the auth context, patient portal, and API routes.
export const demoUser = {
  id: "patient-001",
  mrn: "MRN-48920-A", // Medical Record Number
  name: "Ada Quinn",
  email: "ada@example.com",
  phone: "+1 (555) 234-5678",
  dateOfBirth: "1988-04-14",
  gender: "Female",
  bloodGroup: "O+",
  role: "patient",
  allergies: ["Penicillin", "Latex"],
  primaryPhysician: "Dr. Sarah Jenkins",
  insuranceProvider: "BlueCross Premera Gold (Policy #NY-9921448)",
  emergencyContact: {
    name: "Thomas Quinn",
    relationship: "Spouse",
    phone: "+1 (555) 876-5432",
  },
  createdAt: "2026-01-12T09:24:00.000Z",
};

// Seed appointments for the patient portal
export const demoAppointments = [
  {
    id: "apt-101",
    patientId: "patient-001",
    patientName: "Ada Quinn",
    doctorId: "doc-sarah-jenkins",
    doctorName: "Dr. Sarah Jenkins",
    doctorSpecialty: "Cardiology",
    departmentName: "Cardiology & Vascular Medicine",
    date: "2026-09-02",
    time: "10:30 AM",
    location: "Pavilion A, Room 314",
    status: "Upcoming",
    type: "Follow-up Consultation",
    notes: "Routine 6-month blood pressure review and resting ECG evaluation.",
  },
  {
    id: "apt-102",
    patientId: "patient-001",
    patientName: "Ada Quinn",
    doctorId: "doc-david-chen",
    doctorName: "Dr. David Chen",
    doctorSpecialty: "Orthopedics",
    departmentName: "Orthopedics & Joint Replacement",
    date: "2026-09-18",
    time: "02:00 PM",
    location: "Pavilion C, Room 108",
    status: "Upcoming",
    type: "Post-Therapy Assessment",
    notes: "Right knee mobility follow-up after physical rehabilitation.",
  },
  {
    id: "apt-100",
    patientId: "patient-001",
    patientName: "Ada Quinn",
    doctorId: "doc-sarah-jenkins",
    doctorName: "Dr. Sarah Jenkins",
    doctorSpecialty: "Cardiology",
    departmentName: "Cardiology & Vascular Medicine",
    date: "2026-03-10",
    time: "09:00 AM",
    location: "Pavilion A, Room 314",
    status: "Completed",
    type: "Annual Cardiac Evaluation",
    notes: "Resting echocardiogram normal. Cholesterol profile reviewed.",
  },
];

// Seed medical records
export const demoRecords = [
  {
    id: "rec-801",
    patientId: "patient-001",
    title: "Comprehensive Metabolic & Lipid Panel",
    date: "2026-03-10",
    department: "Diagnostic Laboratory",
    doctorName: "Dr. Sarah Jenkins",
    category: "Lab Results",
    summary: "Total cholesterol: 182 mg/dL, HDL: 58 mg/dL, LDL: 104 mg/dL. Fasting glucose: 91 mg/dL. All within normal limits.",
    status: "Normal",
  },
  {
    id: "rec-802",
    patientId: "patient-001",
    title: "Transthoracic Echocardiogram (2D/Doppler)",
    date: "2026-03-10",
    department: "Cardiology",
    doctorName: "Dr. Sarah Jenkins",
    category: "Imaging Report",
    summary: "Left ventricular ejection fraction (LVEF) preserved at 62%. No significant valvular regurgitation or stenosis.",
    status: "Normal",
  },
  {
    id: "rec-803",
    patientId: "patient-001",
    title: "Right Knee MRI (Non-Contrast)",
    date: "2026-01-22",
    department: "Diagnostic Radiology",
    doctorName: "Dr. Michael Thorne",
    category: "Imaging Report",
    summary: "Mild grade I medial meniscus sprain without full tear. Patellofemoral cartilage intact.",
    status: "Reviewed",
  },
];

// Seed prescriptions
export const demoPrescriptions = [
  {
    id: "rx-301",
    medication: "Lisinopril",
    dosage: "10 mg Oral Tablet",
    frequency: "Once daily in the morning",
    prescribingDoctor: "Dr. Sarah Jenkins",
    department: "Cardiology",
    startDate: "2026-03-10",
    refillsRemaining: 3,
    status: "Active",
    instructions: "Take with water. Monitor blood pressure periodically.",
  },
  {
    id: "rx-302",
    medication: "Atorvastatin Calcium",
    dosage: "20 mg Oral Tablet",
    frequency: "Once daily at bedtime",
    prescribingDoctor: "Dr. Sarah Jenkins",
    department: "Cardiology",
    startDate: "2026-03-10",
    refillsRemaining: 2,
    status: "Active",
    instructions: "Avoid grapefruit consumption while taking this medication.",
  },
];

// Longitudinal vitals & lab trend series for trend timeline visualization
export const demoVitalTrends = [
  {
    id: "trend-ldl",
    metric: "LDL Cholesterol",
    unit: "mg/dL",
    color: "accent",
    refMin: 50,
    refMax: 100,
    goal: "Below 100",
    notes:
      "Six-month response to atorvastatin 20 mg. Trending toward goal; next panel scheduled at the annual review.",
    points: [
      { label: "Oct '25", value: 128 },
      { label: "Nov '25", value: 121 },
      { label: "Dec '25", value: 116 },
      { label: "Jan '26", value: 112 },
      { label: "Feb '26", value: 108 },
      { label: "Mar '26", value: 104 },
    ],
  },
  {
    id: "trend-glucose",
    metric: "Fasting Glucose",
    unit: "mg/dL",
    color: "success",
    refMin: 70,
    refMax: 99,
    goal: "70 - 99",
    notes:
      "Consistent fasting glucose within the normal range. No evidence of impaired fasting glucose on serial panels.",
    points: [
      { label: "Oct '25", value: 94 },
      { label: "Nov '25", value: 92 },
      { label: "Dec '25", value: 91 },
      { label: "Jan '26", value: 93 },
      { label: "Feb '26", value: 89 },
      { label: "Mar '26", value: 91 },
    ],
  },
  {
    id: "trend-bp-sys",
    metric: "Systolic Blood Pressure",
    unit: "mmHg",
    color: "warning",
    refMin: 90,
    refMax: 120,
    goal: "Below 120",
    notes:
      "Home and office readings improving under lisinopril. Consistent with guideline-directed hypertension management.",
    points: [
      { label: "Oct '25", value: 136 },
      { label: "Nov '25", value: 131 },
      { label: "Dec '25", value: 128 },
      { label: "Jan '26", value: 124 },
      { label: "Feb '26", value: 121 },
      { label: "Mar '26", value: 118 },
    ],
  },
  {
    id: "trend-bp-dias",
    metric: "Diastolic Blood Pressure",
    unit: "mmHg",
    color: "info",
    refMin: 60,
    refMax: 80,
    goal: "Below 80",
    notes:
      "Diastolic readings stable within the normal range across all recorded visits.",
    points: [
      { label: "Oct '25", value: 86 },
      { label: "Nov '25", value: 84 },
      { label: "Dec '25", value: 81 },
      { label: "Jan '26", value: 80 },
      { label: "Feb '26", value: 79 },
      { label: "Mar '26", value: 77 },
    ],
  },
  {
    id: "trend-weight",
    metric: "Body Weight",
    unit: "kg",
    color: "accent",
    refMin: 55,
    refMax: 75,
    goal: "Maintain",
    notes:
      "Weight stable over the study period. No clinically significant change requiring intervention.",
    points: [
      { label: "Oct '25", value: 68.4 },
      { label: "Nov '25", value: 68.1 },
      { label: "Dec '25", value: 67.8 },
      { label: "Jan '26", value: 67.5 },
      { label: "Feb '26", value: 67.9 },
      { label: "Mar '26", value: 67.6 },
    ],
  },
];

// Health education library articles
export const healthArticles = [
  {
    id: "art-001",
    slug: "managing-blood-pressure-at-home",
    title: "Managing Blood Pressure Between Visits",
    category: "Cardiovascular Health",
    readTime: "6 min read",
    date: "2026-08-18",
    author: "Dr. Sarah Jenkins, Cardiology",
    excerpt:
      "A practical guide to accurate home blood pressure monitoring, lifestyle levers, and knowing when to call your care team.",
    sections: [
      "Measuring your blood pressure correctly at home matters more than how often you measure it. Sit quietly for five minutes first, place the cuff on a bare upper arm at heart level, and take three readings one minute apart. Record the average rather than the lowest number.",
      "Consistent readings above 130/80 mmHg on a home monitor should be discussed with your physician. Before any medication adjustment, keep a one-week log with morning and evening readings. Bring that log to your next visit.",
      "Non-drug measures remain the first lever: reducing sodium toward 1,500 to 2,000 mg per day, brisk physical activity most days of the week, and limiting alcohol. Changes show up in readings within two to four weeks when sustained.",
      "Call your care team the same day if you record two separate readings above 180/120 mmHg, experience chest pain, severe headache, or shortness of breath, or notice vision changes. These are not reasons to wait for a scheduled appointment.",
    ],
    takeaways: [
      "Use the correct cuff size and measure at heart level",
      "Keep a one-week log before any medication discussion",
      "Sustained readings above 130/80 warrant a clinic review",
      "Readings above 180/120 with symptoms require same-day care",
    ],
  },
  {
    id: "art-002",
    slug: "understanding-your-lipid-panel",
    title: "Understanding Your Lipid Panel Results",
    category: "Cardiovascular Health",
    readTime: "5 min read",
    date: "2026-07-30",
    author: "Dr. Sarah Jenkins, Cardiology",
    excerpt:
      "What LDL, HDL, triglycerides, and total cholesterol actually mean, and how your doctor uses them to guide treatment.",
    sections: [
      "A standard lipid panel reports four numbers: total cholesterol, LDL (the plaque-forming fraction), HDL (the protective fraction), and triglycerides. The LDL value is usually the main treatment target because it is the component most directly linked to arterial plaque buildup.",
      "Guidelines base LDL goals on your overall cardiovascular risk, not on a single universal number. For someone with diabetes or a history of heart disease, the target is far lower, often below 70 mg/dL. Your personal goal should come from your clinician, not from a lab reference range.",
      "Lifestyle changes lower LDL most reliably when combined, not in isolation. Soluble fiber from oats, legumes, and fruits, replacement of saturated fats with unsaturated plant oils, and weight reduction each contribute a few percentage points.",
      "Statins are prescribed when lifestyle alone is unlikely to reach your goal within a reasonable window. Response is measured at six to twelve weeks with a repeat panel. Side effects are less common than patients often expect, and dose adjustments usually resolve any discomfort.",
    ],
    takeaways: [
      "LDL is the primary treatment target",
      "Your LDL goal depends on your personal risk profile",
      "Combined lifestyle changes lower LDL most reliably",
      "A repeat panel at 6-12 weeks measures statin response",
    ],
  },
  {
    id: "art-003",
    slug: "preparing-for-diagnostic-imaging",
    title: "Preparing for MRI, CT, and Ultrasound Exams",
    category: "Diagnostics",
    readTime: "4 min read",
    date: "2026-06-22",
    author: "Dr. Michael Thorne, Radiology",
    excerpt:
      "What to expect the day of your scan, which preparations matter, and how to make the exam run smoothly.",
    sections: [
      "Preparation depends on the exam. For an MRI without contrast there is rarely any fasting requirement, but every implant you have must be disclosed, including pacemakers, cochlear implants, and old surgical clips, even if you think they are safe.",
      "CT scans with IV contrast generally require fasting for four hours beforehand. Tell the technologist about allergies to iodinated contrast, kidney disease, or metformin use, as each can change how the injection is managed.",
      "Ultrasound preparation is organ-specific. Abdominal exams often need fasting, while pelvic exams may require a full bladder. Wear comfortable clothing without metal fasteners and arrive 15 minutes early for the safety screening.",
      "During the exam you will hear loud machine noises during an MRI. Foam ear protection is provided. You can speak with the technologist throughout, and holding still is the most important factor for image quality.",
    ],
    takeaways: [
      "Disclose every implant before an MRI",
      "Fast four hours before a CT with contrast",
      "Ultrasound prep depends on the organ being scanned",
      "Allow 15 minutes for the safety screening",
    ],
  },
  {
    id: "art-004",
    slug: "statin-side-effects-facts",
    title: "Statins, Muscle Symptoms, and What the Evidence Shows",
    category: "Medication Safety",
    readTime: "7 min read",
    date: "2026-05-14",
    author: "Dr. Sarah Jenkins, Cardiology",
    excerpt:
      "A candid look at one of the most common medication concerns in preventive cardiology, with a practical response plan.",
    sections: [
      "Muscle aches are the most frequently reported statin side effect, yet clinical trials consistently show they occur at similar rates in placebo groups. The nocebo effect explains part of the perception, but genuine statin-associated muscle symptoms are real and deserve attention.",
      "When symptoms appear after starting or increasing a statin, the standard approach is to confirm the pattern with a two-week washout, then rechallenge with the same or a lower dose. Symptoms that return only on the drug are the ones that matter.",
      "Only a small minority who genuinely cannot tolerate any statin need to stop treatment entirely. Alternatives include a lower dose of a more potent statin, a long-acting formulation taken weekly, or a non-statin agent such as ezetimibe.",
      "Do not stop a statin on your own. Abrupt discontinuation after six months or more of use removes protection against plaque progression, and the conversation about alternatives should happen with your prescriber while you continue the current dose.",
    ],
    takeaways: [
      "Muscle symptoms in trials occur equally with placebo",
      "Confirm a true pattern with a washout and rechallenge",
      "Most patients can continue some form of lipid therapy",
      "Never stop a statin without speaking to your prescriber",
    ],
  },
  {
    id: "art-005",
    slug: "healthy-fasting-blood-glucose",
    title: "Keeping Fasting Blood Glucose in a Healthy Range",
    category: "Metabolic Health",
    readTime: "5 min read",
    date: "2026-04-09",
    author: "Dr. David Chen, Internal Medicine",
    excerpt:
      "Why fasting glucose matters, what the numbers mean, and the habits that keep metabolic health on track.",
    sections: [
      "Fasting glucose is measured after at least eight hours without food. A value below 100 mg/dL is considered normal, 100 to 125 mg/dL indicates impaired fasting glucose, commonly called prediabetes, and 126 mg/dL or higher on two occasions meets the threshold for diabetes.",
      "Prediabetes is reversible in many cases. The Diabetes Prevention Program showed that a 7 percent weight reduction combined with 150 minutes of moderate activity per week reduced progression to diabetes by more than half over three years.",
      "Carbohydrate quality matters more than carbohydrate quantity. Favor whole grains, legumes, and vegetables over refined grains and added sugars. Protein and fiber at breakfast blunt the morning glucose rise that often shows up in labs.",
      "Serial testing is how trends are caught. If you have a family history of diabetes, elevated fasting glucose, or a sedentary pattern, request a hemoglobin A1c, which reflects average glucose over the prior two to three months.",
    ],
    takeaways: [
      "Fasting glucose below 100 mg/dL is normal",
      "Prediabetes is reversible with weight and activity changes",
      "Carbohydrate quality matters as much as quantity",
      "A1c gives a three-month average picture",
    ],
  },
  {
    id: "art-006",
    slug: "knee-recovery-after-therapy",
    title: "Recovering After Knee Injury: Expected Milestones",
    category: "Orthopedics",
    readTime: "5 min read",
    date: "2026-03-02",
    author: "Dr. David Chen, Orthopedics",
    excerpt:
      "A realistic timeline for soft tissue knee recovery, the difference between good pain and signal pain, and when to push on.",
    sections: [
      "After a meniscal sprain or similar soft tissue injury, the first two weeks focus on reducing swelling, restoring range of motion, and offloading the joint. Ice, elevation, and painless range-of-motion exercises are the priority before any strengthening begins.",
      "A common mistake is to return to activity as soon as walking feels comfortable. Painless walking rarely means the tissue has remodeled. Strength retraining should progress through guided phases: isometric, then closed-chain, then dynamic loading.",
      "Distinguish good discomfort from signal pain. Muscle soreness during strengthening is expected. Sharp pain, locking, giving way, or swelling that reappears more than two hours after activity are signals to back off and contact your therapist.",
      "Most non-operative soft tissue knee injuries tolerate a return to light sport within six to eight weeks, with full return often closer to twelve weeks. Follow-up imaging is only ordered if clinical milestones stall for two consecutive weeks.",
    ],
    takeaways: [
      "Control swelling and restore motion before strengthening",
      "Progress through guided strengthening phases",
      "Locking or giving way are reasons to stop and check in",
      "Allow 6-8 weeks for light sport in most cases",
    ],
  },
];

