// Single source of truth for hospital metadata, navigation menus,
// departments, doctors, services, and demo data.

// Canonical deployment URL. Override with NEXT_PUBLIC_SITE_URL in env.
export const siteConfig = {
  name: "Providence General Hospital",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://www.providencegeneral.org",
  ogImage: "/opengraph-image.png",
};

export const hospitalInfo = {
  name: "Providence General Hospital",
  shortName: "Providence Health",
  tagline: "Advanced clinical care, compassionate service, 24/7 readiness.",
  establishedYear: 1984,
  licenseNumber: "MED-HOSP-NY-8942",
  phone: {
    emergency: "+1 (800) 555-0911",
    ambulance: "+1 (800) 555-0911",
    appointments: "+1 (800) 555-0144",
    general: "+1 (800) 555-0199",
  },
  email: "care@providencegeneral.org",
  address: {
    street: "742 Evergreen Medical Parkway, Suite 100",
    city: "Metro City",
    state: "NY",
    zip: "10001",
    directionsUrl: "https://maps.google.com",
  },
  hours: {
    emergency: "24 hours / 7 days / 365 days a year",
    outpatient: "Mon – Fri: 7:30 AM – 7:00 PM | Sat: 8:00 AM – 3:00 PM",
    diagnostics: "Mon – Sat: 6:30 AM – 8:00 PM | Sun: 8:00 AM – 2:00 PM",
    visitingHours: "Daily: 9:00 AM – 8:00 PM (ICU: 11:00 AM – 2:00 PM & 5:00 PM – 7:00 PM)",
    pharmacy: "24/7 In-House Service",
  },
  accreditations: [
    "Joint Commission (JCAHO) Gold Seal Certified",
    "Level I Trauma Center & Comprehensive Stroke Center",
    "Magnet Recognized for Nursing Excellence",
  ],
};

export const emergencyHotlines = [
  {
    title: "Ambulance & Trauma Resuscitation",
    phone: "+1 (800) 555-0911",
    subtitle: "Direct line to hospital dispatch (24/7)",
    urgent: true,
  },
  {
    title: "Acute Stroke & Chest Pain Triage",
    phone: "+1 (800) 555-0922",
    subtitle: "Rapid intervention team on standby",
    urgent: true,
  },
  {
    title: "Pediatric Emergency Desk",
    phone: "+1 (800) 555-0933",
    subtitle: "Dedicated pediatric trauma bay",
    urgent: false,
  },
  {
    title: "National Poison Control Center",
    phone: "1-800-222-1222",
    subtitle: "Free, confidential 24/7 guidance",
    urgent: false,
  },
];

export const publicNav = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Departments", href: "/departments" },
  { label: "Doctors", href: "/doctors" },
  { label: "Resources", href: "/resources" },
  { label: "Contact", href: "/contact" },
];

export const legalNav = [
  { label: "Privacy Policy", href: "/legal/privacy" },
  { label: "Terms of Use", href: "/legal/terms" },
  { label: "Accessibility", href: "/legal/accessibility" },
];

export const appNav = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Appointments", href: "/dashboard/appointments" },
  { label: "Telehealth Room", href: "/dashboard/telehealth" },
  { label: "Care Messages", href: "/dashboard/messages" },
  { label: "Medical Records", href: "/dashboard/records" },
  { label: "Prescriptions", href: "/dashboard/prescriptions" },
  { label: "Billing & Invoices", href: "/dashboard/billing" },
  { label: "Staff Workstation", href: "/staff" },
  { label: "Profile", href: "/profile" },
  { label: "Settings", href: "/settings" },
];

export const departments = [
  {
    id: "dept-cardiology",
    slug: "cardiology",
    name: "Cardiology & Vascular Medicine",
    shortName: "Cardiology",
    icon: "heart",
    description:
      "Comprehensive cardiovascular care, interventional catheterization, electrophysiology, and advanced heart failure treatment.",
    headOfDept: "Dr. Sarah Jenkins, MD, FACC",
    location: "Pavilion A, 3rd Floor",
    phoneExt: "Ext. 3100",
    emergencySupported: true,
    services: [
      "Diagnostic Echocardiography & ECG",
      "Cardiac Catheterization & Angioplasty",
      "Pacemaker & Defibrillator Implantation",
      "Cardiac Rehabilitation Program",
    ],
  },
  {
    id: "dept-neurology",
    slug: "neurology",
    name: "Neurology & Neurosurgery",
    shortName: "Neurology",
    icon: "brain",
    description:
      "Dedicated diagnosis and minimally invasive surgical management for stroke, epilepsy, spinal trauma, and neurodegenerative disorders.",
    headOfDept: "Dr. Marcus Vance, MD, PhD",
    location: "Pavilion B, 4th Floor",
    phoneExt: "Ext. 4200",
    emergencySupported: true,
    services: [
      "24/7 Acute Stroke Intervention",
      "Minimally Invasive Brain & Spine Surgery",
      "Comprehensive Epilepsy Monitoring",
      "Neuro-Rehabilitation & Physical Therapy",
    ],
  },
  {
    id: "dept-pediatrics",
    slug: "pediatrics",
    name: "Pediatrics & Neonatology",
    shortName: "Pediatrics",
    icon: "baby",
    description:
      "Compassionate, specialized clinical care for infants, children, and teenagers, supported by a Level III Neonatal Intensive Care Unit (NICU).",
    headOfDept: "Dr. Elena Rostova, MD, FAAP",
    location: "Children's Health Pavilion, 2nd Floor",
    phoneExt: "Ext. 2100",
    emergencySupported: true,
    services: [
      "Well-Child Exams & Immunizations",
      "Level III Neonatal ICU (NICU)",
      "Pediatric Allergy & Pulmonology",
      "Pediatric Emergency Triage",
    ],
  },
  {
    id: "dept-orthopedics",
    slug: "orthopedics",
    name: "Orthopedics & Joint Replacement",
    shortName: "Orthopedics",
    icon: "bone",
    description:
      "Pioneering robotic joint replacement, sports injury reconstruction, spinal correction, and physical therapy rehabilitation.",
    headOfDept: "Dr. David Chen, MD, FAAOS",
    location: "Pavilion C, 1st Floor",
    phoneExt: "Ext. 1500",
    emergencySupported: true,
    services: [
      "Robotic Total Hip & Knee Replacement",
      "Arthroscopic Sports Medicine",
      "Complex Fracture & Trauma Care",
      "Dedicated Outpatient Physical Therapy",
    ],
  },
  {
    id: "dept-oncology",
    slug: "oncology",
    name: "Oncology & Comprehensive Cancer Center",
    shortName: "Oncology",
    icon: "ribbon",
    description:
      "Precision oncology with multidisciplinary tumor boards, advanced radiation therapy, targeted immunotherapy, and supportive patient care.",
    headOfDept: "Dr. Amina Al-Mansoor, MD",
    location: "Hope Pavilion, 5th Floor",
    phoneExt: "Ext. 5100",
    emergencySupported: false,
    services: [
      "Chemotherapy & Targeted Immunotherapy",
      "Precision Stereotactic Radiosurgery",
      "Genetic Cancer Risk Assessment",
      "Oncology Nutrition & Psychological Support",
    ],
  },
  {
    id: "dept-obstetrics",
    slug: "obstetrics-gynecology",
    name: "Obstetrics & Women's Health",
    shortName: "Women's Health",
    icon: "female",
    description:
      "Comprehensive maternal-fetal medicine, private labor and delivery suites, gynecologic surgery, and holistic reproductive health.",
    headOfDept: "Dr. Robert Gallagher, MD, FACOG",
    location: "Women's Health Center, 2nd Floor",
    phoneExt: "Ext. 2400",
    emergencySupported: true,
    services: [
      "High-Risk Prenatal Care",
      "Private Family Birthing Suites",
      "Minimally Invasive Gynecological Surgery",
      "Menopause & Hormonal Health Clinic",
    ],
  },
  {
    id: "dept-emergency",
    slug: "emergency-trauma",
    name: "Emergency Medicine & Level I Trauma",
    shortName: "Emergency",
    icon: "ambulance",
    description:
      "Round-the-clock emergency medical services, rapid resuscitation bays, certified trauma surgeons, and acute triage.",
    headOfDept: "Dr. Priya Patel, MD, FACEP",
    location: "Ground Floor East Entrance",
    phoneExt: "Ext. 9110",
    emergencySupported: true,
    services: [
      "24/7 Level I Trauma Care",
      "Rapid Chest Pain Assessment",
      "Acute Stroke & TPA Administration",
      "Dedicated Pediatric ER Bay",
    ],
  },
  {
    id: "dept-radiology",
    slug: "radiology-imaging",
    name: "Diagnostic Radiology & Imaging",
    shortName: "Radiology",
    icon: "scan",
    description:
      "Advanced 3T MRI, 128-slice dual-source CT, digital 3D mammography, nuclear medicine, and ultrasound diagnostics.",
    headOfDept: "Dr. Michael Thorne, MD, FACR",
    location: "Central Diagnostics, Lower Level 1",
    phoneExt: "Ext. 1200",
    emergencySupported: true,
    services: [
      "High-Field 3.0T MRI & CT Scans",
      "3D Digital Tomosynthesis Mammography",
      "Ultrasound & Doppler Vascular Imaging",
      "Interventional Radiology Biopsies",
    ],
  },
];

export const doctors = [
  {
    id: "doc-sarah-jenkins",
    name: "Dr. Sarah Jenkins",
    title: "Chief of Cardiovascular Medicine",
    specialty: "Cardiology",
    departmentId: "dept-cardiology",
    departmentSlug: "cardiology",
    qualifications: "MD (Johns Hopkins), FACC, FSCAI",
    experienceYears: 18,
    languages: ["English", "Spanish"],
    consultationFee: "$180",
    rating: 4.9,
    reviewCount: 342,
    availableDays: ["Monday", "Tuesday", "Thursday"],
    availableSlots: ["09:00 AM", "10:30 AM", "01:30 PM", "03:00 PM", "04:30 PM"],
    bio: "Dr. Jenkins is a nationally recognized interventional cardiologist specializing in complex coronary interventions, heart failure management, and preventive cardiology.",
    contactEmail: "s.jenkins@providencegeneral.org",
  },
  {
    id: "doc-marcus-vance",
    name: "Dr. Marcus Vance",
    title: "Director of Neurosurgery",
    specialty: "Neurology",
    departmentId: "dept-neurology",
    departmentSlug: "neurology",
    qualifications: "MD, PhD (Harvard Medical School), FAANS",
    experienceYears: 21,
    languages: ["English"],
    consultationFee: "$220",
    rating: 4.95,
    reviewCount: 289,
    availableDays: ["Tuesday", "Wednesday", "Friday"],
    availableSlots: ["08:30 AM", "10:00 AM", "11:30 AM", "02:00 PM"],
    bio: "Dr. Vance specializes in robotic neurosurgery, minimally invasive spine reconstruction, and cerebral aneurysm repair.",
    contactEmail: "m.vance@providencegeneral.org",
  },
  {
    id: "doc-elena-rostova",
    name: "Dr. Elena Rostova",
    title: "Head of Pediatric Care",
    specialty: "Pediatrics",
    departmentId: "dept-pediatrics",
    departmentSlug: "pediatrics",
    qualifications: "MD (Columbia University), FAAP",
    experienceYears: 14,
    languages: ["English", "Russian"],
    consultationFee: "$140",
    rating: 4.92,
    reviewCount: 410,
    availableDays: ["Monday", "Wednesday", "Thursday", "Friday"],
    availableSlots: ["09:00 AM", "10:00 AM", "11:00 AM", "01:00 PM", "02:30 PM", "04:00 PM"],
    bio: "Dr. Rostova is dedicated to family-centered pediatric care, child development, and the management of chronic childhood illnesses.",
    contactEmail: "e.rostova@providencegeneral.org",
  },
  {
    id: "doc-david-chen",
    name: "Dr. David Chen",
    title: "Senior Orthopedic Surgeon",
    specialty: "Orthopedics",
    departmentId: "dept-orthopedics",
    departmentSlug: "orthopedics",
    qualifications: "MD (Stanford University), FAAOS",
    experienceYears: 16,
    languages: ["English", "Mandarin"],
    consultationFee: "$190",
    rating: 4.88,
    reviewCount: 315,
    availableDays: ["Monday", "Wednesday", "Friday"],
    availableSlots: ["08:00 AM", "09:30 AM", "11:00 AM", "01:30 PM", "03:00 PM"],
    bio: "Dr. Chen is a pioneer in computer-navigated robotic joint replacements and minimally invasive arthroscopic sports injury treatments.",
    contactEmail: "d.chen@providencegeneral.org",
  },
  {
    id: "doc-amina-almansoor",
    name: "Dr. Amina Al-Mansoor",
    title: "Lead Medical Oncologist",
    specialty: "Oncology",
    departmentId: "dept-oncology",
    departmentSlug: "oncology",
    qualifications: "MD (Oxford University), MRCP, FASCO",
    experienceYears: 17,
    languages: ["English", "Arabic", "French"],
    consultationFee: "$200",
    rating: 4.96,
    reviewCount: 260,
    availableDays: ["Monday", "Tuesday", "Thursday"],
    availableSlots: ["10:00 AM", "11:30 AM", "02:00 PM", "03:30 PM"],
    bio: "Dr. Al-Mansoor specializes in precision targeted oncology, novel clinical trials, and personalized immunotherapy protocols.",
    contactEmail: "a.almansoor@providencegeneral.org",
  },
  {
    id: "doc-robert-gallagher",
    name: "Dr. Robert Gallagher",
    title: "Director of Maternal-Fetal Medicine",
    specialty: "Obstetrics & Gynecology",
    departmentId: "dept-obstetrics",
    departmentSlug: "obstetrics-gynecology",
    qualifications: "MD (UCSF), FACOG",
    experienceYears: 19,
    languages: ["English"],
    consultationFee: "$170",
    rating: 4.91,
    reviewCount: 375,
    availableDays: ["Tuesday", "Wednesday", "Thursday"],
    availableSlots: ["09:00 AM", "10:30 AM", "01:00 PM", "02:30 PM", "04:00 PM"],
    bio: "Dr. Gallagher has delivered over 3,000 infants and has special expertise in high-risk obstetrics and advanced fetal ultrasound monitoring.",
    contactEmail: "r.gallagher@providencegeneral.org",
  },
  {
    id: "doc-priya-patel",
    name: "Dr. Priya Patel",
    title: "Clinical Director of Emergency Medicine",
    specialty: "Emergency Medicine",
    departmentId: "dept-emergency",
    departmentSlug: "emergency-trauma",
    qualifications: "MD (Penn Medicine), FACEP",
    experienceYears: 15,
    languages: ["English", "Hindi", "Gujarati"],
    consultationFee: "$160",
    rating: 4.94,
    reviewCount: 520,
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    availableSlots: ["24/7 Emergency Triage Rotation"],
    bio: "Dr. Patel leads the emergency resuscitation bay and Level I trauma team with expertise in acute airway management and disaster preparedness.",
    contactEmail: "p.patel@providencegeneral.org",
  },
  {
    id: "doc-michael-thorne",
    name: "Dr. Michael Thorne",
    title: "Chief of Diagnostic Imaging",
    specialty: "Radiology",
    departmentId: "dept-radiology",
    departmentSlug: "radiology-imaging",
    qualifications: "MD (Yale University), FACR",
    experienceYears: 20,
    languages: ["English"],
    consultationFee: "$150",
    rating: 4.87,
    reviewCount: 198,
    availableDays: ["Monday", "Tuesday", "Wednesday", "Friday"],
    availableSlots: ["08:30 AM", "10:00 AM", "01:00 PM", "03:00 PM"],
    bio: "Dr. Thorne is an expert in neuroradiology, oncologic imaging, and 3T MRI diagnostics.",
    contactEmail: "m.thorne@providencegeneral.org",
  },
];

export const services = [
  {
    id: "serv-emergency",
    name: "24/7 Emergency & Level I Trauma",
    category: "Critical Care",
    description:
      "Fully staffed trauma center with immediate surgical capabilities, rapid CT access, and pediatric emergency bays.",
    badge: "24/7 Available",
  },
  {
    id: "serv-diagnostics",
    name: "Diagnostic Laboratory & Imaging",
    category: "Diagnostics",
    description:
      "Same-day routine and specialized blood tests, 3T MRI, 128-slice CT scans, digital ultrasound, and pathology.",
    badge: "Same-Day Results",
  },
  {
    id: "serv-surgery",
    name: "Minimally Invasive & Robotic Surgery",
    category: "Surgical Care",
    description:
      "State-of-the-art da Vinci robotic surgery suites minimizing recovery time, pain, and hospital stay durations.",
    badge: "Advanced Tech",
  },
  {
    id: "serv-checkups",
    name: "Comprehensive Preventive Health Packages",
    category: "Wellness & Prevention",
    description:
      "Customized executive wellness screenings, cardiovascular risk profiles, and cancer prevention assessments.",
    badge: "Preventive",
  },
  {
    id: "serv-telehealth",
    name: "Telehealth & Virtual Consultations",
    category: "Outpatient",
    description:
      "Secure, encrypted video consultations with board-certified physicians for follow-ups, minor illnesses, and prescriptions.",
    badge: "Virtual Care",
  },
  {
    id: "serv-pharmacy",
    name: "24/7 In-House Patient Pharmacy",
    category: "Pharmacy",
    description:
      "On-site prescription fulfillment, medication reconciliation, and pharmacist consultations around the clock.",
    badge: "24/7 Service",
  },
];

// Demo patient used to seed the auth context, patient portal, and API routes.
export const demoUser = {
  id: "patient-001",
  mrn: "MRN-48920-A", // Medical Record Number
  name: "Ada Quinn",
  email: "ada@example.com",
  phone: "+1 (555) 234-5678",
  dateOfBirth: "1988-04-14",
  gender: "Female",
  bloodGroup: "O+",
  role: "patient",
  allergies: ["Penicillin", "Latex"],
  primaryPhysician: "Dr. Sarah Jenkins",
  insuranceProvider: "BlueCross Premera Gold (Policy #NY-9921448)",
  emergencyContact: {
    name: "Thomas Quinn",
    relationship: "Spouse",
    phone: "+1 (555) 876-5432",
  },
  createdAt: "2026-01-12T09:24:00.000Z",
};

// Seed appointments for the patient portal
export const demoAppointments = [
  {
    id: "apt-101",
    patientId: "patient-001",
    patientName: "Ada Quinn",
    doctorId: "doc-sarah-jenkins",
    doctorName: "Dr. Sarah Jenkins",
    doctorSpecialty: "Cardiology",
    departmentName: "Cardiology & Vascular Medicine",
    date: "2026-09-02",
    time: "10:30 AM",
    location: "Pavilion A, Room 314",
    status: "Upcoming",
    type: "Follow-up Consultation",
    notes: "Routine 6-month blood pressure review and resting ECG evaluation.",
  },
  {
    id: "apt-102",
    patientId: "patient-001",
    patientName: "Ada Quinn",
    doctorId: "doc-david-chen",
    doctorName: "Dr. David Chen",
    doctorSpecialty: "Orthopedics",
    departmentName: "Orthopedics & Joint Replacement",
    date: "2026-09-18",
    time: "02:00 PM",
    location: "Pavilion C, Room 108",
    status: "Upcoming",
    type: "Post-Therapy Assessment",
    notes: "Right knee mobility follow-up after physical rehabilitation.",
  },
  {
    id: "apt-100",
    patientId: "patient-001",
    patientName: "Ada Quinn",
    doctorId: "doc-sarah-jenkins",
    doctorName: "Dr. Sarah Jenkins",
    doctorSpecialty: "Cardiology",
    departmentName: "Cardiology & Vascular Medicine",
    date: "2026-03-10",
    time: "09:00 AM",
    location: "Pavilion A, Room 314",
    status: "Completed",
    type: "Annual Cardiac Evaluation",
    notes: "Resting echocardiogram normal. Cholesterol profile reviewed.",
  },
];

// Seed medical records
export const demoRecords = [
  {
    id: "rec-801",
    patientId: "patient-001",
    title: "Comprehensive Metabolic & Lipid Panel",
    date: "2026-03-10",
    department: "Diagnostic Laboratory",
    doctorName: "Dr. Sarah Jenkins",
    category: "Lab Results",
    summary: "Total cholesterol: 182 mg/dL, HDL: 58 mg/dL, LDL: 104 mg/dL. Fasting glucose: 91 mg/dL. All within normal limits.",
    status: "Normal",
    downloadUrl: "#",
  },
  {
    id: "rec-802",
    patientId: "patient-001",
    title: "Transthoracic Echocardiogram (2D/Doppler)",
    date: "2026-03-10",
    department: "Cardiology",
    doctorName: "Dr. Sarah Jenkins",
    category: "Imaging Report",
    summary: "Left ventricular ejection fraction (LVEF) preserved at 62%. No significant valvular regurgitation or stenosis.",
    status: "Normal",
    downloadUrl: "#",
  },
  {
    id: "rec-803",
    patientId: "patient-001",
    title: "Right Knee MRI (Non-Contrast)",
    date: "2026-01-22",
    department: "Diagnostic Radiology",
    doctorName: "Dr. Michael Thorne",
    category: "Imaging Report",
    summary: "Mild grade I medial meniscus sprain without full tear. Patellofemoral cartilage intact.",
    status: "Reviewed",
    downloadUrl: "#",
  },
];

// Seed prescriptions
export const demoPrescriptions = [
  {
    id: "rx-301",
    medication: "Lisinopril",
    dosage: "10 mg Oral Tablet",
    frequency: "Once daily in the morning",
    prescribingDoctor: "Dr. Sarah Jenkins",
    department: "Cardiology",
    startDate: "2026-03-10",
    refillsRemaining: 3,
    status: "Active",
    instructions: "Take with water. Monitor blood pressure periodically.",
  },
  {
    id: "rx-302",
    medication: "Atorvastatin Calcium",
    dosage: "20 mg Oral Tablet",
    frequency: "Once daily at bedtime",
    prescribingDoctor: "Dr. Sarah Jenkins",
    department: "Cardiology",
    startDate: "2026-03-10",
    refillsRemaining: 2,
    status: "Active",
    instructions: "Avoid grapefruit consumption while taking this medication.",
  },
];

